=== thiema/StruP/easyflow/src/easyflow/custom/tool/schema/Easyflow.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="urn:de.thiema.easyflow/types" 
	xmlns="urn:de.thiema.easyflow/types" 
	elementFormDefault="qualified">
<xs:element name="tool" type="Tool" />
	<xs:complexType name="Tool">
		<xs:sequence>
			<xs:element name="description" type="xs:string" />
	        <xs:element name="interpreter" type="Interpreter" />
	        <xs:element name="command" type="Command" />
	        <xs:element maxOccurs="unbounded" minOccurs="0" name="input" type="DataPort" />
	        <xs:element maxOccurs="unbounded" minOccurs="0" name="output" type="DataPort" />
	        <xs:element maxOccurs="unbounded" minOccurs="0" name="param" type="Param" />
	        <xs:element name="help" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="version" type="xs:string" />
			
	</xs:complexType>
	
	<xs:complexType name="Interpreter">
		<xs:attribute name="exe" type="xs:string" />
	</xs:complexType>
	 
	<xs:complexType name="Command" mixed="true">
		<xs:simpleContent>
			<xs:extension base="xs:string">
			
				<xs:attribute name="interpreter" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
		
	</xs:complexType>
	
	<xs:complexType name="DataPort">
		<xs:sequence>
	    	<xs:element maxOccurs="unbounded" minOccurs="0" name="data" />
	    </xs:sequence>
	    <xs:attribute name="name" type="xs:string" />
	    <xs:attribute name="format" type="xs:string" />
	    <xs:attribute name="label" type="xs:string" />
	</xs:complexType>            
	            
	<xs:complexType name="Param">
	    <xs:sequence>
	    	<xs:element maxOccurs="unbounded" minOccurs="0" name="option" />
	    </xs:sequence>
	    <xs:attribute name="name" type="xs:string" />
	    <xs:attribute name="type" type="xs:string" />
	    <xs:attribute name="value" type="xs:string" />
	    <xs:attribute name="label" type="xs:string" />
	    <xs:attribute name="help" type="xs:string" />
	    <xs:attribute name="optional" type="xs:boolean" />
	</xs:complexType>
	            
	
	
</xs:schema>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/sequencing/tool_definitions/tool.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:de.thiema.easyflow/types"
	xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd" id="id_TA3"
	name="TA" version="1.0">
	<description>
		The any dummy tool
	</description>
	<interpreter exe="python"></interpreter>
	<command interpreter="python">
		any.py $input $output
	</command>
	<param key="input_bam" type="data" label="" seperator=" " named="true">
		<name value="-i"/>
		<name value="--input"/>
	</param>
	<param key="param1" type="integer" value="-1" label="the label"
		help="help info" />
	<param key="param2" type="select"
		label="Type of BAQ calculation to apply in the engine" help="help info">
		<option value="OFF" selected="True">OFF</option>
		<option value="CALCULATE_AS_NECESSARY">CALCULATE_AS_NECESSARY</option>
		<option value="RECALCULATE">RECALCULATE</option>
	</param>
	<param key="option1" type="integer" value="-1" label="the label"
		help="help info" optional="true" />
	<param key="output_bam" type="data" output="true" named="true">
		<name value="-o"/>
	</param>
	<param key="output_log" type="data" output="true" named="true">
		<name value="--log" type="long"/>	
	</param>
	<data key="input_bam" format="bam" label="${tool.name} on ${on_string} (BAM)" />
	<data key="output_bam" format="bam" label="${tool.name} on ${on_string} (BAM)" />
	<data key="output_log" format="txt" label="${tool.name} on ${on_string} (log)" />
	<help>
		The help page for any tool.
	</help>
</tool>
