=== thiema/StruP/easyflow/bin/easyflow/custom/tool/schema/Easyflow.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:de.thiema.easyflow/types" xmlns="urn:de.thiema.easyflow/types"
	elementFormDefault="qualified">
	<xs:element name="tool" type="Tool" />
	<xs:complexType name="Tool">
		<xs:sequence>
			<xs:element name="source" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" />
			<xs:element name="interpreter" type="Interpreter" />
			<xs:element name="command" type="Command" />
			<xs:element maxOccurs="unbounded" minOccurs="0" name="param"
				type="Param" />
			<xs:element maxOccurs="unbounded" minOccurs="0" name="data"
				type="DataPort" />
			<xs:element name="help" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="version" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Interpreter">
		<xs:attribute name="exe" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Command" mixed="true">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="interpreter" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="DataPort">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="data" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="format" type="xs:string" />
		<xs:attribute name="label" type="xs:string" />
	</xs:complexType>


	<xs:complexType name="Param">
		<xs:sequence>
			<xs:element name="option" type="Option" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="name" type="ParamName" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="dependency" type="Dependency" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="key" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="type" type="xs:string" />
		<xs:attribute name="value" type="xs:string" />
		<xs:attribute name="label" type="xs:string" />
		<xs:attribute name="help" type="xs:string" />
		<xs:attribute name="optional" type="xs:boolean" />
		<xs:attribute name="multiple" type="xs:boolean" />
		<xs:attribute name="multipleValue" type="xs:boolean" />		
	</xs:complexType>
	
	<xs:complexType name="Option">
		<xs:attribute name="value"/>
	</xs:complexType>
	<xs:complexType name="ParamName">
		<xs:attribute name="value"/>
	</xs:complexType>
	<xs:complexType name="Dependency">
		<xs:attribute name="key"/>
		<xs:attribute name="name"/>
		<xs:attribute name="uri"/>
	</xs:complexType>

</xs:schema>

=== thiema/StruP/easyflow/bin/easyflow/custom/examples/sequencing/tool_definitions/pavgi_picard/rgPicardInsertSize.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      name="Insertion size metrics"
      id="PicardInsertSize"
      version="1.56.0">
  <description>for PAIRED data</description>
  <requirements>
      <requirement type="package" version="1.56.0">picard</requirement>
   </requirements>
  
  
    <param name="input_file" type="data" format="bam,sam"
          help="If empty, upload or import a SAM/BAM dataset."
          label="SAM/BAM dataset to generate statistics for">
      <key>If</key>
   </param>
    <param name="out_prefix" type="text" help="Use this remind you what the job was for"
          label="Title for the output file">
      <key>Use</key>
   </param>
    <param name="deviations" type="float"
          help="See Picard documentation: Generate mean, sd and plots by trimming the data down to MEDIAN + DEVIATIONS*MEDIAN_ABSOLUTE_DEVIATION"
          label="Deviations">
      <key>See</key>
   </param>
     <param name="histWidth" type="integer"
          help="Explicitly sets the histogram width option - leave 0 to ignore"
          label="Histogram width">
      <key>Explicitly</key>
   </param>
     <param name="minPct" type="float"
          help="Discard any data categories (out of FR, TANDEM, RF) that have fewer than this percentage of overall reads"
          label="Minimum percentage">
      <key>Discard</key>
   </param>
     <param name="malevel" type="select"
          help="Level(s) at which metrics will be accumulated"
          label="Metric Accumulation Level">
      <key>Level(s)</key>
   </param>
  
  
    <param name="html_file" type="data" format="html"
          label="InsertSize_${out_prefix}.html"
          output="true"/>
  
    <data name="html_file" format="html" label="InsertSize_${out_prefix}.html"/>
  
  
  
</tool>

=== thiema/StruP/easyflow/bin/easyflow/custom/examples/sequencing/tool_definitions/pavgi_picard/picard_ReorderSam.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      name="Reorder SAM/BAM"
      id="picard_ReorderSam"
      version="1.56.0">
  <requirements>
      <requirement type="package" version="1.56.0">picard</requirement>
   </requirements>
  
  
    <param name="inputFile" type="data" format="bam,sam"
          help="If empty, upload or import a SAM/BAM dataset."
          label="SAM/BAM dataset to be reordered">
      <key>If</key>
   </param>
    <param name="refFile" type="data" format="fasta" label="Using reference file"/>
   <param name="speciesName" type="text" label="Species name"/>
   <param name="buildName" type="text" label="Build name"/>
   <param name="truncateSeqNames" type="boolean"
          label="Truncate sequence names after first whitespace"
          defaultValue="true">
      <key>true</key>
   </param>
    <param name="allowIncDictConcord" type="boolean"
          help="Allows a partial overlap of the BAM contigs with the new reference sequence contigs."
          label="Allow incomplete dict concordance?"
          defaultValue="true">
      <key>true</key>
      <key>Allows</key>
   </param>
    <param name="allowContigLenDiscord" type="boolean"
          help="This is dangerous--don't check it unless you know exactly what you're doing!"
          label="Allow contig length discordance?"
          defaultValue="true">
      <key>true</key>
      <key>This</key>
   </param>
    <param name="outputFormat" type="boolean" help="Uncheck for SAM output"
          label="Output BAM instead of SAM"
          defaultValue="true">
      <key>bam</key>
      <key>Uncheck</key>
   </param>
  
  
    <param name="outFile" type="data" format="bam"
          label="${tool.name} on ${on_string}: reordered ${outputFormat}"
          output="true"/>
  
    <data name="outFile" format="bam"
         label="${tool.name} on ${on_string}: reordered ${outputFormat}">
      <change_format>
        <when input="outputFormat" value="sam" format="sam"/>
      </change_format>
    </data>
  
  
  
</tool>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/sequencing/tool_definitions/pavgi_picard/rgPicardGCBiasMetrics.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      name="SAM/BAM GC Bias Metrics"
      id="PicardGCBiasMetrics"
      version="1.56.0">
  
  <requirements>
      <requirement type="package" version="1.56.0">picard</requirement>
   </requirements>
  
    <param name="input_file" type="data" format="sam,bam"
          help="If empty, upload or import a SAM/BAM dataset."
          label="SAM/BAM dataset to generateGC bias metrics">
      <key>If</key>
   </param>
    <param name="out_prefix" type="text" help="Use this remind you what the job was for."
          label="Title for the output file">
      <key>Use</key>
   </param>
    <param name="ownFile" type="data" format="fasta"
          help="This option works best for relatively small genomes. If you are working with large human-sized genomes, send request to Galaxy team for adding your reference to this Galaxy instance by using 'Help' link at the top of Galaxy interface."
          label="Select a reference genome from history">
      <key>This</key>
   </param>
    <param name="windowsize" type="integer"
          help="The size of windows on the genome that are used to bin reads. Default value: 100."
          label="GC minimum window size">
      <key>The</key>
   </param>
    <param name="mingenomefrac" type="float"
          help="For summary metrics, exclude GC windows that include less than this fraction of the genome. Default value: 1.0E-5."
          label="Minimum Genome Fraction">
      <key>For</key>
   </param>
    

  
  
    <param name="html_file" type="data" format="html" label="${out_prefix}.html"
          output="true"/>
  
    <data name="html_file" format="html" label="${out_prefix}.html"/>
  
  
  
</tool>
