=== thiema/StruP/easyflow/bin/easyflow/custom/tool/schema/Easyflow.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:de.thiema.easyflow/types" xmlns="urn:de.thiema.easyflow/types"
	elementFormDefault="qualified">
	<xs:element name="tool" type="Tool" />
	<xs:complexType name="Tool">
		<xs:sequence>
			<xs:element name="source" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" />
			<xs:element name="interpreter" type="Interpreter" />
			<xs:element name="command" type="Command" />
			<xs:element maxOccurs="unbounded" minOccurs="0" name="param"
				type="Param" />
			<xs:element maxOccurs="unbounded" minOccurs="0" name="data"
				type="DataPort" />
			<xs:element name="help" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="version" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Interpreter">
		<xs:attribute name="exe" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Command" mixed="true">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="interpreter" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="DataPort">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="data" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="format" type="xs:string" />
		<xs:attribute name="label" type="xs:string" />
	</xs:complexType>


	<xs:complexType name="Param">
		<xs:sequence>
			<xs:element name="option" type="Option" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="name" type="ParamName" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="dependency" type="Dependency" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="key" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="type" type="xs:string" />
		<xs:attribute name="value" type="xs:string" />
		<xs:attribute name="label" type="xs:string" />
		<xs:attribute name="help" type="xs:string" />
		<xs:attribute name="optional" type="xs:boolean" />
		<xs:attribute name="multiple" type="xs:boolean" />
		<xs:attribute name="multipleValue" type="xs:boolean" />		
	</xs:complexType>
	
	<xs:complexType name="Option">
		<xs:attribute name="value"/>
	</xs:complexType>
	<xs:complexType name="ParamName">
		<xs:attribute name="value"/>
	</xs:complexType>
	<xs:complexType name="Dependency">
		<xs:attribute name="key"/>
		<xs:attribute name="name"/>
		<xs:attribute name="uri"/>
	</xs:complexType>

</xs:schema>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/sequencing/tool_definitions/bedtools-galaxy/intersectBed_bam.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      id="bedtools_intersectbed_bam"
      name="Find BAM alignments that overlap intervals in another file"
      version="0.1.0">

   <requirements>
      <requirement type="binary">intersectBed</requirement>
   </requirements>




    <param name="inputA" type="data" format="bed,bam"
          label="Which alignments in this BAM file"/>
    <param name="inputB" type="data" format="bed"
          label="overlap intervaks in this BED file"/>
    <param name="split" type="boolean"
          help="If set, the coverage will be calculated based the spliced intervals only. For BAM files, this inspects the CIGAR N operation to infer the blocks for computing coverage. For BED12 files, this inspects the BlockCount, BlockStarts, and BlockEnds fields (i.e., columns 10,11,12). If this option is not set, coverage will be calculated based on the interval's START/END coordinates, and would include introns in the case of RNAseq data."
          label="Treat split/spliced BAM or BED12 entries as distinct BED intervals when computing coverage."
          defaultValue="true">
      <key type="short">split</key>
      <key>If</key>
   </param>
    
    <param name="strand" type="select" label="Calculate coverage based on"/>
    
    <param name="fraction" type="text"
          help="Alignments are only retained if the overlap with the an interval in the BED file comprises at least this fraction of the BAM alignment's length.  For example, to require that the overlap affects 50% of the BAM alignment, use 0.50"
          label="Minimum overlap required as a fraction of the BAM alignment"
          optional="true">
      <key>Alignments</key>
   </param>
    
    <param name="reciprocal" type="boolean"
          help="If set, the overlap between the BAM alignment and the BED interval must affect the above fraction of both the alignment and the BED interval."
          label="Require reciprocal overlap."
          defaultValue="true">
      <key type="short">r</key>
      <key>If</key>
   </param>
    
    <param name="invert" type="boolean"
          label="Report only those alignments that **do not** overlap the BED file."
          defaultValue="true">
      <key type="short">v</key>
   </param>
    



    <param name="output" type="data" format="bam"
          label="Intersection of ${inputA.name} and ${inputB.name}"
          output="true"/>

    <data name="output" format="bam"
         label="Intersection of ${inputA.name} and ${inputB.name}"
         metadata_source="inputA"/>



</tool>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/sequencing/tool_definitions/pavgi_picard/rgPicardHsMetrics.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      name="SAM/BAM Hybrid Selection Metrics"
      id="PicardHsMetrics"
      version="1.56.0">
  <description>for targeted resequencing data</description>
  
  <requirements>
      <requirement type="package" version="1.56.0">picard</requirement>
   </requirements>
  
    <param name="input_file" type="data" format="sam,bam"
          label="SAM/BAM dataset to generate statistics for"/>
    <param name="out_prefix" type="text" help="Use to remind you what the job was for."
          label="Title for the output file">
      <key>Use</key>
   </param>
    <param name="bait_bed" type="data" format="bed,interval"
          help="Note specific format requirements below!"
          label="Bait intervals: Sequences for bait in the design">
      <key>Note</key>
   </param>
    <param name="target_bed" type="data" format="bed,interval"
          help="Note specific format requirements below!"
          label="Target intervals: Sequences for targets in the design">
      <key>Note</key>
   </param>
    
  
  
    <param name="html_file" type="data" format="html" label="${out_prefix}.html"
          output="true"/>
  
    <data name="html_file" format="html" label="${out_prefix}.html"/>
  
  
  
</tool>

=== thiema/StruP/src/easyflow/custom/examples/reseq/tool_definitions/bedtools-galaxy/genomeCoverageBed_bedgraph.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      id="bedtools_genomecoveragebed_bedgraph"
      name="Create a BedGraph of genome coverage"
      version="0.1.0">

    <requirements>
        <requirement type="binary">genomeCoverageBed</requirement>
    </requirements>

    

    
        <param name="input" type="data" format="bed,bam"
          label="The BAM or BED file from which coverage should be computed"/>

        <param name="zero_regions" type="boolean"
          help="If set, regions without any coverage will also be reported."
          label="Report regions with zero coverage"
          defaultValue="true">
      <key type="short">bga</key>
      <key>If</key>
   </param>

        <param name="split" type="boolean"
          help="If set, the coverage will be calculated based the spliced intervals only. For BAM files, this inspects the CIGAR N operation to infer the blocks for computing coverage. For BED12 files, this inspects the BlockCount, BlockStarts, and BlockEnds fields (i.e., columns 10,11,12). If this option is not set, coverage will be calculated based on the interval's START/END coordinates, and would include introns in the case of RNAseq data."
          label="Treat split/spliced BAM or BED12 entries as distinct BED intervals when computing coverage."
          defaultValue="true">
      <key type="short">split</key>
      <key>If</key>
   </param>

        <param name="strand" type="select" label="Calculate coverage based on"/>

        <param name="scale" type="text"
          help="Each BEDGRAPH coverage value is multiplied by this factor before being reported. Useful for normalizing coverage by, e.g., reads per million (RPM)"
          label="Scale the coverage by a constant factor"
          optional="true">
      <key>Each</key>
   </param>
    

    
        <param name="output" type="data" format="bedgraph"
          label="${input.name} (Genome Coverage BedGraph)"
          output="true"/>
    
        <data name="output" format="bedgraph"
         label="${input.name} (Genome Coverage BedGraph)"
         metadata_source="input"/>
    
    
</tool>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/sequencing/tool_definitions/pavgi_picard/rgPicardASMetrics.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      name="SAM/BAM Alignment Summary Metrics"
      id="PicardASMetrics"
      version="1.56.0">
  
  <requirements>
      <requirement type="package" version="1.56.0">picard</requirement>
   </requirements>
  
    <param name="input_file" type="data" format="sam,bam"
          help="If empty, upload or import a SAM/BAM dataset."
          label="SAM/BAM dataset to generate statistics for"/>
    <param name="out_prefix" type="text" help="Use this remind you what the job was for."
          label="Title for the output file"/>

      <param name="ownFile" type="data" format="fasta"
          help="This option works best for relatively small genomes. If you are working with large human-sized genomes, send request to Galaxy team for adding your reference to this Galaxy instance by using 'Help' link at the top of Galaxy interface."
          label="Select a reference genome from history"/>
    <param name="sorted" type="boolean" label="Assume the input file is already sorted"
          default_value="true">
      <key>true</key>
   </param>
    <param name="bisulphite" type="boolean"
          label="Input file contains Bisulphite sequenced reads"
          default_value="true">
      <key>true</key>
   </param>
    <param name="adaptors" type="text" help="One per line if multiple"
          label="Adapter sequences"/>
    <param name="maxinsert" type="integer"
          label="Larger paired end reads and inter-chromosomal pairs considered chimeric "/>
  
  
    <param name="html_file" type="data" format="html" label="${out_prefix}.html"
          output="true"/>
  
    <data name="html_file" format="html" label="${out_prefix}.html"/>
  
  
  
</tool>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/sequencing/tool_definitions/pavgi_picard/rgPicardMarkDups.easyflow.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      name="Mark Duplicate reads"
      id="rgPicardMarkDups"
      version="1.56.0">
  
  <requirements>
      <requirement type="package" version="1.56.0">picard</requirement>
   </requirements>
  
    <param name="input_file" type="data" format="bam,sam"
          help="If empty, upload or import a SAM/BAM dataset."
          label="SAM/BAM dataset to mark duplicates in"/>
    <param name="out_prefix" type="text" help="Use this remind you what the job was for"
          label="Title for the output file"/>
    <param name="remDups" type="boolean"
          help="If true do not write duplicates to the output file instead of writing them with appropriate flags set."
          label="Remove duplicates from output file"
          defaultValue="true">
      <key>true</key>
   </param>
    <param name="assumeSorted" type="boolean"
          help="If true assume input data are already sorted (most Galaxy SAM/BAM should be)."
          label="Assume reads are already ordered"
          defaultValue="true">
      <key>true</key>
   </param>
     <param name="readRegex" type="text"
          help="Names are parsed to extract: tile/region, x coordinate and y coordinate, to estimate optical duplication rate"
          label="Regular expression that can be used to parse read names in the incoming SAM file"/>
     <param name="optDupeDist" type="integer"
          help="e.g. 5-10 pixels. Later Illumina software versions multiply pixel values by 10, in which case 50-100."
          label="The maximum offset between two duplicate clusters in order to consider them optical duplicates."/>

  
  
    <param name="out_file" type="data" format="bam" label="MarkDups_${out_prefix}.bam"
          output="true"/>
    <param name="html_file" type="data" format="html" label="MarkDups_${out_prefix}.html"
          output="true"/>
  
    <data name="out_file" format="bam" label="MarkDups_${out_prefix}.bam"/>
    <data name="html_file" format="html" label="MarkDups_${out_prefix}.html"/>
  
  
  
  
</tool>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/sequencing/tool_definitions/pavgi_picard/rgPicardLibComplexity.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      name="Estimate Library Complexity"
      id="rgEstLibComp"
      version="1.56.0">
  <requirements>
      <requirement type="package" version="1.56.0">picard</requirement>
   </requirements>
  
  
    <param name="input_file" type="data" format="bam,sam"
          help="If empty, upload or import a SAM/BAM dataset."
          label="SAM/BAM dataset">
      <key>If</key>
   </param>
    <param name="out_prefix" type="text" help="Use this remind you what the job was for."
          label="Title for the output file">
      <key>Use</key>
   </param>
    <param name="minIDbases" type="integer"
          help="Total_reads / 4^max_id_bases reads will be compared at a time. Lower numbers = more accurate results and exponentially more time/memory."
          label="Minimum identical bases at starts of reads for grouping">
      <key>Total_reads</key>
   </param>
     <param name="maxDiff" type="float"
          help="The maximum rate of differences between two reads to call them identical"
          label="Maximum difference rate for identical reads">
      <key>The</key>
   </param>
     <param name="minMeanQ" type="integer"
          help="The minimum mean quality of bases in a read pair. Lower average quality reads filtered out from all calculations"
          label="Minimum percentage">
      <key>The</key>
   </param>
     <param name="readRegex" type="text"
          help="Names are parsed to extract: tile/region, x coordinate and y coordinate, to estimate optical duplication rate"
          label="Regular expression that can be used to parse read names in the incoming SAM file">
      <key>Names</key>
   </param>
     <param name="optDupeDist" type="text"
          help="e.g. 5-10 pixels. Later Illumina software versions multiply pixel values by 10, in which case 50-100"
          label="The maximum offset between two duplicte clusters in order to consider them optical duplicates.">
      <key>e.g.</key>
   </param>

  
  
    <param name="html_file" type="data" format="html"
          label="${out_prefix}_lib_complexity.html"
          output="true"/>
  
    <data name="html_file" format="html" label="${out_prefix}_lib_complexity.html"/>
  
  
  
</tool>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/reseq/tool_definitions/bedtools-galaxy/bamToBed.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      id="bedtools_bamtobed"
      name="Convert from BAM to BED."
      version="0.1.0">

   <requirements>
      <requirement type="binary">bamToBed</requirement>
   </requirements>




    <param name="input" type="data" format="bam"
          label="Convert the following BAM file to BED"/>
    <param name="option" type="select" label="What type of BED output would you like"/>
    <param name="split" type="boolean"
          label="Report spliced BAM alignments as separate BED entries"
          defaultValue="true">
      <key type="short">split</key>
   </param>
    <param name="ed_score" type="boolean"
          label="Use alignment's edit-distance for BED score"
          defaultValue="true">
      <key type="short">ed</key>
   </param>
    <param name="tag" type="text"
          label="Use other NUMERIC BAM alignment tag as the BED score"
          optional="true"/>



    <param name="output" type="data" format="bed" label="${input.name} (as BED)"
          output="true"/>

    <data name="output" format="bed" label="${input.name} (as BED)"
         metadata_source="input"/>



</tool>

=== thiema/StruP/easyflow/src/easyflow/custom/examples/sequencing/tool_definitions/bedtools-galaxy/coverageBed_counts.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="urn:de.thiema.easyflow/types"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:de.thiema.easyflow/types Easyflow.xsd"
      id="bedtools_coveragebed_counts"
      name="Count intervals in one file overlapping intervals in another file."
      version="0.1.0">

   <requirements>
      <requirement type="binary">coverageBed</requirement>
   </requirements>




    <param name="inputA" type="data" format="bed,bam"
          label="Count how many intervals in this BED or BAM file (source)"/>
    <param name="inputB" type="data" format="bed"
          label="overlap the intervals in this BED file (target)"/>
    <param name="split" type="boolean"
          help="If set, the coverage will be calculated based the spliced intervals only. For BAM files, this inspects the CIGAR N operation to infer the blocks for computing coverage. For BED12 files, this inspects the BlockCount, BlockStarts, and BlockEnds fields (i.e., columns 10,11,12). If this option is not set, coverage will be calculated based on the interval's START/END coordinates, and would include introns in the case of RNAseq data."
          label="Treat split/spliced BAM or BED12 entries as distinct BED intervals when computing coverage."
          defaultValue="true">
      <key type="short">split</key>
      <key>If</key>
   </param>
    
    <param name="strand" type="select" label="Count"/>



    <param name="output" type="data" format="bed"
          label="count of overlaps in ${inputA.name} on ${inputB.name}"
          output="true"/>

    <data name="output" format="bed"
         label="count of overlaps in ${inputA.name} on ${inputB.name}"
         metadata_source="inputB"/>



</tool>
